[package]
name = "nix-options-doc"
version = "0.1.0"
authors = ["Chinmay D. Pai <chinmaydpai@gmail.com>"]
edition = "2021"
license = "MIT"
description = "Generate Markdown documentation for NixOS module options"
keywords = ["nixos", "markdown", "documentation"]
repository = "https://github.com/Thunderbottom/nix-options-doc"
homepage = "https://github.com/Thunderbottom/nix-options-doc"
readme = "README.md"
include = ["src/**/*", "LICENSE*", "README.md"]
publish = false

[dependencies]
clap = { version = "4.5", features = ["derive"] }
git2 = "0.20"
rnix = "0.12"
rowan = "0.15.16"
serde = { version = "1.0", features = ["derive"] }
tempfile = "3.16"
walkdir = "2.5"
